name: Run All Tests on pull request

on:
  pull_request:
    types:
      - opened
      - synchronize  # Zdarzenie wywoływane podczas każdej aktualizacji (np. nowego commita) na pull request
    branches:
      - 'release'
      - 'develop'

jobs:
  test_all:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
      issues: read

    steps:
      - name: Checkout head branch of PR from GitHub
        uses: actions/checkout@v3
        with:
          ref: ${{github.head_ref}}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Test with Maven
        run: mvn -B test

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            target/surefire-reports/*.xml

      - name: Check test results
        id: check_test_results
        run: echo "::set-output name=success::$(find target/surefire-reports/ -type f -name '*.xml' | xargs grep -L '<failure' | xargs grep -L '<error')"

  publish_approval:
    needs: test_all
    runs-on: ubuntu-latest
    steps:
      - name: Check test results
        id: check_test_results
        run: echo "::set-output name=success::$(find ${{ needs.test_all.outputs.artifacts-path }} -type f -name '*.xml' | xargs grep -L '<failure' | xargs grep -L '<error')"

      - name: Approve PR if tests passed
        if: steps.check_test_results.outputs.success == 'true'
        run: echo "Tests passed, you can merge now!"