name: Run All Tests on pull request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - 'release'
      - 'develop'

jobs:
  test_all:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
      issues: read

    steps:
      - name: Checkout head branch of PR from GitHub
        if: github.event.action == 'opened' || github.event.action == 'synchronize'
        uses: actions/checkout@v3
        with:
          ref: ${{github.head_ref}}

      - name: Checkout base branch of PR from GitHub
        if: github.event.pull_request.merged == true
        uses: actions/checkout@v3
        with:
          ref: ${{github.base_ref}}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Test with Maven
        run: |
          # Ustaw zmienną środowiskową z ścieżką pliku tymczasowego
          export TEMP_FILE_PATH=target/testowy_plik.txt

          # Uruchom testy Maven
          mvn -B test

          # Skopiuj utworzony plik tymczasowy do katalogu dostępnego dla GitHub Actions
          cp $TEMP_FILE_PATH $GITHUB_WORKSPACE
          
          # Ustaw zmienną środowiskową dostępną dla kolejnych kroków
          echo "TEMP_FILE_PATH=$TEMP_FILE_PATH" >> $GITHUB_ENV

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            target/surefire-reports/*.xml

