name: Run All Tests on pull request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - 'release'
      - 'develop'

jobs:
  test_all:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
      issues: read

    steps:
      - name: Checkout head branch of PR from GitHub
        if: github.event.action == 'opened' || github.event.action == 'synchronize'
        uses: actions/checkout@v3
        with:
          ref: ${{github.head_ref}}

      - name: Checkout base branch of PR from GitHub
        if: github.event.pull_request.merged == true
        uses: actions/checkout@v3
        with:
          ref: ${{github.base_ref}}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Test with Maven
        run: mvn -B test

      - name: Save Test Output Files
        run: |
          # Możesz dostosować ścieżki i rozszerzenia plików w zależności od Twoich testów
          cp target/testowy_plik.txt $GITHUB_WORKSPACE
        if: always()

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            target/surefire-reports/*.xml

      - name: Upload Test Output Files
        uses: actions/upload-artifact@v2
        with:
          name: test-output
          path: $GITHUB_WORKSPACE/target
        if: always()
