name: Auto Tag Release

on:
  push:
    branches:
      - release
      
jobs:
    bumpTag:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Bump version and push tag
          id: tag_version
          uses: mathieudutour/github-tag-action@v6.1
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
